"""sync_random_calling_models

Revision ID: 04c8c5f6adab
Revises: a9f0357750b6
Create Date: 2025-08-11 15:16:35.549508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04c8c5f6adab'
down_revision: Union[str, None] = 'a9f0357750b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('random_call_preferences', sa.Column('call_frequency', sa.String(), nullable=True))
    op.add_column('random_call_preferences', sa.Column('time_windows', sa.JSON(), nullable=True))
    op.alter_column('random_call_preferences', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('random_call_preferences', 'min_hours_between_calls')
    op.drop_column('random_call_preferences', 'min_calls_per_day')
    op.drop_column('random_call_preferences', 'last_random_call_time')
    op.drop_column('random_call_preferences', 'calls_made_today')
    op.drop_column('random_call_preferences', 'exclude_themes')
    op.drop_column('random_call_preferences', 'start_time_hour')
    op.drop_column('random_call_preferences', 'active_days')
    op.drop_column('random_call_preferences', 'max_calls_per_day')
    op.drop_column('random_call_preferences', 'last_reset_date')
    op.drop_column('random_call_preferences', 'end_time_hour')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('random_call_preferences', sa.Column('end_time_hour', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('random_call_preferences', sa.Column('last_reset_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('random_call_preferences', sa.Column('max_calls_per_day', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('random_call_preferences', sa.Column('active_days', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('random_call_preferences', sa.Column('start_time_hour', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('random_call_preferences', sa.Column('exclude_themes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('random_call_preferences', sa.Column('calls_made_today', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('random_call_preferences', sa.Column('last_random_call_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('random_call_preferences', sa.Column('min_calls_per_day', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('random_call_preferences', sa.Column('min_hours_between_calls', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('random_call_preferences', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('random_call_preferences', 'time_windows')
    op.drop_column('random_call_preferences', 'call_frequency')
    # ### end Alembic commands ###
