"""add_google_calendar_credentials_table

Revision ID: 0e73a4c793fe
Revises: f3a4d8dcf585
Create Date: 2025-04-14 12:24:09.177400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e73a4c793fe'
down_revision: Union[str, None] = 'f3a4d8dcf585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'token_type')
    op.drop_column('tokens', 'refresh_token')
    op.drop_column('tokens', 'is_valid')
    op.drop_column('tokens', 'access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('access_token', sa.TEXT(), nullable=True))
    op.add_column('tokens', sa.Column('is_valid', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True))
    op.add_column('tokens', sa.Column('refresh_token', sa.TEXT(), nullable=True))
    op.add_column('tokens', sa.Column('token_type', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
