"""remove_random_calling_tables

Revision ID: 11cc92f1b64b
Revises: 04c8c5f6adab
Create Date: 2025-08-11 15:22:19.022196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11cc92f1b64b'
down_revision: Union[str, None] = '04c8c5f6adab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_random_call_preferences_id'), table_name='random_call_preferences')
    op.drop_table('random_call_preferences')
    op.drop_index(op.f('ix_generated_scenarios_id'), table_name='generated_scenarios')
    op.drop_table('generated_scenarios')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_scenarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('persona', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('voice_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('generation_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('themes_used', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('generation_model', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('times_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_used', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('context_metadata', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('generated_scenarios_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('generated_scenarios_pkey'))
    )
    op.create_index(op.f('ix_generated_scenarios_id'), 'generated_scenarios', ['id'], unique=False)
    op.create_table('random_call_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('persona_themes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('user_context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('call_frequency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('time_windows', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('random_call_preferences_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('random_call_preferences_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('random_call_preferences_user_id_key'))
    )
    op.create_index(op.f('ix_random_call_preferences_id'), 'random_call_preferences', ['id'], unique=False)
    # ### end Alembic commands ###
