"""enhance_anonymous_onboarding_for_mobile_4_step_flow

Revision ID: 28f18c529584
Revises: a92b4d9d7998
Create Date: 2025-08-24 15:24:28.824268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28f18c529584'
down_revision: Union[str, None] = 'a92b4d9d7998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anonymous_onboarding_sessions', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('anonymous_onboarding_sessions', sa.Column('preferred_voice', sa.String(), nullable=True))
    op.add_column('anonymous_onboarding_sessions', sa.Column('notifications_enabled', sa.Boolean(), nullable=True))
    op.add_column('anonymous_onboarding_sessions', sa.Column('welcome_completed', sa.Boolean(), nullable=True))
    op.add_column('anonymous_onboarding_sessions', sa.Column('profile_completed', sa.Boolean(), nullable=True))
    op.add_column('anonymous_onboarding_sessions', sa.Column('tutorial_completed', sa.Boolean(), nullable=True))
    op.add_column('anonymous_onboarding_sessions', sa.Column('current_step', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anonymous_onboarding_sessions', 'current_step')
    op.drop_column('anonymous_onboarding_sessions', 'tutorial_completed')
    op.drop_column('anonymous_onboarding_sessions', 'profile_completed')
    op.drop_column('anonymous_onboarding_sessions', 'welcome_completed')
    op.drop_column('anonymous_onboarding_sessions', 'notifications_enabled')
    op.drop_column('anonymous_onboarding_sessions', 'preferred_voice')
    op.drop_column('anonymous_onboarding_sessions', 'phone_number')
    # ### end Alembic commands ###
