"""add duration_limit to conversation

Revision ID: 2fea136ed473
Revises: eb266d814df4
Create Date: 2025-07-31 12:43:19.827092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fea136ed473'
down_revision: Union[str, None] = 'eb266d814df4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('duration_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'duration_limit')
    # ### end Alembic commands ###
