"""Add StoredTwilioTranscript model

Revision ID: 40e131ef24ae
Revises: b9e2b583b876
Create Date: 2025-06-08 09:53:36.663365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40e131ef24ae'
down_revision: Union[str, None] = 'b9e2b583b876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
