"""Add calendar_processed field to SMS messages

Revision ID: 52c42c78dae5
Revises: fe0b74938e1a
Create Date: 2025-08-27 16:26:31.293400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52c42c78dae5'
down_revision: Union[str, None] = 'fe0b74938e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_messages', sa.Column('calendar_processed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sms_messages', 'calendar_processed')
    # ### end Alembic commands ###
