"""add_subscription_status_column

Revision ID: 949f6ba259b3
Revises: c517e4534e6b
Create Date: 2025-06-20 12:39:50.580086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '949f6ba259b3'
down_revision: Union[str, None] = 'c517e4534e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_limits', sa.Column('subscription_status', sa.Enum('ACTIVE', 'CANCELLED', 'BILLING_RETRY', 'EXPIRED', 'GRACE_PERIOD', 'PENDING', name='subscriptionstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage_limits', 'subscription_status')
    # ### end Alembic commands ###
