"""sync_database_to_current_state

Revision ID: 96925727854f
Revises: 11cc92f1b64b
Create Date: 2025-08-11 21:59:00.950228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96925727854f'
down_revision: Union[str, None] = '11cc92f1b64b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('call_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('scenario', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_schedules_id'), 'call_schedules', ['id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('scenario', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('call_sid', sa.String(), nullable=True),
    sa.Column('recording_sid', sa.String(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('transcript_sid', sa.String(), nullable=True),
    sa.Column('duration_limit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_table('custom_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('persona', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('voice_type', sa.String(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_scenarios_id'), 'custom_scenarios', ['id'], unique=False)
    op.create_index(op.f('ix_custom_scenarios_scenario_id'), 'custom_scenarios', ['scenario_id'], unique=True)
    op.create_table('google_calendar_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('openai_api_key', sa.String(), nullable=True),
    sa.Column('twilio_account_sid', sa.String(), nullable=True),
    sa.Column('twilio_auth_token', sa.String(), nullable=True),
    sa.Column('twilio_phone_number', sa.String(), nullable=True),
    sa.Column('twilio_vi_sid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_provider_credentials_id'), 'provider_credentials', ['id'], unique=False)
    op.create_table('stored_twilio_transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transcript_sid', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('date_created', sa.String(), nullable=False),
    sa.Column('date_updated', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(), nullable=False),
    sa.Column('sentences', sa.JSON(), nullable=False),
    sa.Column('call_sid', sa.String(), nullable=True),
    sa.Column('scenario_name', sa.String(), nullable=True),
    sa.Column('call_direction', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stored_twilio_transcripts_id'), 'stored_twilio_transcripts', ['id'], unique=False)
    op.create_index(op.f('ix_stored_twilio_transcripts_transcript_sid'), 'stored_twilio_transcripts', ['transcript_sid'], unique=True)
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('token_type', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token')
    )
    op.create_index(op.f('ix_tokens_id'), 'tokens', ['id'], unique=False)
    op.create_table('transcript_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcript_sid', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=True),
    sa.Column('sentences_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('call_date', sa.DateTime(), nullable=True),
    sa.Column('participant_info', sa.JSON(), nullable=True),
    sa.Column('conversation_flow', sa.JSON(), nullable=True),
    sa.Column('media_url', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('call_direction', sa.String(), nullable=True),
    sa.Column('scenario_name', sa.String(), nullable=True),
    sa.Column('summary_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_records_transcript_sid'), 'transcript_records', ['transcript_sid'], unique=True)
    op.create_table('usage_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('app_type', sa.Enum('MOBILE_CONSUMER', 'WEB_BUSINESS', name='apptype'), nullable=False),
    sa.Column('calls_made_today', sa.Integer(), nullable=True),
    sa.Column('calls_made_this_week', sa.Integer(), nullable=True),
    sa.Column('calls_made_this_month', sa.Integer(), nullable=True),
    sa.Column('calls_made_total', sa.Integer(), nullable=True),
    sa.Column('last_call_date', sa.Date(), nullable=True),
    sa.Column('week_start_date', sa.Date(), nullable=True),
    sa.Column('month_start_date', sa.Date(), nullable=True),
    sa.Column('trial_calls_remaining', sa.Integer(), nullable=True),
    sa.Column('trial_calls_used', sa.Integer(), nullable=True),
    sa.Column('trial_start_date', sa.DateTime(), nullable=True),
    sa.Column('trial_end_date', sa.DateTime(), nullable=True),
    sa.Column('is_trial_active', sa.Boolean(), nullable=True),
    sa.Column('subscription_tier', sa.Enum('MOBILE_FREE_TRIAL', 'MOBILE_BASIC', 'MOBILE_PREMIUM', 'BUSINESS_FREE_TRIAL', 'BUSINESS_BASIC', 'BUSINESS_PROFESSIONAL', 'BUSINESS_ENTERPRISE', name='subscriptiontier'), nullable=True),
    sa.Column('is_subscribed', sa.Boolean(), nullable=True),
    sa.Column('subscription_start_date', sa.DateTime(), nullable=True),
    sa.Column('subscription_end_date', sa.DateTime(), nullable=True),
    sa.Column('subscription_status', sa.Enum('ACTIVE', 'CANCELLED', 'BILLING_RETRY', 'EXPIRED', 'GRACE_PERIOD', 'PENDING', name='subscriptionstatus'), nullable=True),
    sa.Column('weekly_call_limit', sa.Integer(), nullable=True),
    sa.Column('monthly_call_limit', sa.Integer(), nullable=True),
    sa.Column('billing_cycle', sa.String(), nullable=True),
    sa.Column('last_payment_date', sa.DateTime(), nullable=True),
    sa.Column('next_payment_date', sa.DateTime(), nullable=True),
    sa.Column('app_store_transaction_id', sa.String(), nullable=True),
    sa.Column('app_store_product_id', sa.String(), nullable=True),
    sa.Column('total_call_duration_this_week', sa.Integer(), nullable=True),
    sa.Column('total_call_duration_this_month', sa.Integer(), nullable=True),
    sa.Column('addon_calls_remaining', sa.Integer(), nullable=True),
    sa.Column('addon_calls_expiry', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_usage_limits_id'), 'usage_limits', ['id'], unique=False)
    op.create_table('user_onboarding_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone_number_setup', sa.Boolean(), nullable=True),
    sa.Column('calendar_connected', sa.Boolean(), nullable=True),
    sa.Column('first_scenario_created', sa.Boolean(), nullable=True),
    sa.Column('welcome_call_completed', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('current_step', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_onboarding_status_id'), 'user_onboarding_status', ['id'], unique=False)
    op.create_table('user_phone_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('twilio_sid', sa.String(), nullable=False),
    sa.Column('friendly_name', sa.String(), nullable=True),
    sa.Column('date_provisioned', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('voice_capable', sa.Boolean(), nullable=True),
    sa.Column('sms_capable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('twilio_sid')
    )
    op.create_index(op.f('ix_user_phone_numbers_id'), 'user_phone_numbers', ['id'], unique=False)
    op.create_index(op.f('ix_user_phone_numbers_phone_number'), 'user_phone_numbers', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_phone_numbers_phone_number'), table_name='user_phone_numbers')
    op.drop_index(op.f('ix_user_phone_numbers_id'), table_name='user_phone_numbers')
    op.drop_table('user_phone_numbers')
    op.drop_index(op.f('ix_user_onboarding_status_id'), table_name='user_onboarding_status')
    op.drop_table('user_onboarding_status')
    op.drop_index(op.f('ix_usage_limits_id'), table_name='usage_limits')
    op.drop_table('usage_limits')
    op.drop_index(op.f('ix_transcript_records_transcript_sid'), table_name='transcript_records')
    op.drop_table('transcript_records')
    op.drop_index(op.f('ix_tokens_id'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_stored_twilio_transcripts_transcript_sid'), table_name='stored_twilio_transcripts')
    op.drop_index(op.f('ix_stored_twilio_transcripts_id'), table_name='stored_twilio_transcripts')
    op.drop_table('stored_twilio_transcripts')
    op.drop_index(op.f('ix_provider_credentials_id'), table_name='provider_credentials')
    op.drop_table('provider_credentials')
    op.drop_table('google_calendar_credentials')
    op.drop_index(op.f('ix_custom_scenarios_scenario_id'), table_name='custom_scenarios')
    op.drop_index(op.f('ix_custom_scenarios_id'), table_name='custom_scenarios')
    op.drop_table('custom_scenarios')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_call_schedules_id'), table_name='call_schedules')
    op.drop_table('call_schedules')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
