"""add_user_profile_fields

Revision ID: a92b4d9d7998
Revises: f20c14b69504
Create Date: 2025-08-22 16:57:56.904403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a92b4d9d7998'
down_revision: Union[str, None] = 'f20c14b69504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('preferred_voice', sa.String(), nullable=True))
    op.add_column('users', sa.Column('notifications_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notifications_enabled')
    op.drop_column('users', 'preferred_voice')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
