"""Add SMS conversation and message tables

Revision ID: bec058360a70
Revises: 28f18c529584
Create Date: 2025-08-26 20:38:05.427447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bec058360a70'
down_revision: Union[str, None] = '28f18c529584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('twilio_phone_number', sa.String(), nullable=False),
    sa.Column('conversation_context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('customer_interest', sa.String(), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=True),
    sa.Column('lead_score', sa.Integer(), nullable=True),
    sa.Column('conversion_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_conversations_id'), 'sms_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_sms_conversations_phone_number'), 'sms_conversations', ['phone_number'], unique=False)
    op.create_table('sms_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('message_sid', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('from_number', sa.String(), nullable=False),
    sa.Column('to_number', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.Column('intent_detected', sa.String(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('entities_extracted', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['sms_conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_sid')
    )
    op.create_index(op.f('ix_sms_messages_id'), 'sms_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sms_messages_id'), table_name='sms_messages')
    op.drop_table('sms_messages')
    op.drop_index(op.f('ix_sms_conversations_phone_number'), table_name='sms_conversations')
    op.drop_index(op.f('ix_sms_conversations_id'), table_name='sms_conversations')
    op.drop_table('sms_conversations')
    # ### end Alembic commands ###
