"""update_token_model_fields

Revision ID: c4a8511542e3
Revises: 3e22308a5d75
Create Date: 2025-07-30 11:47:26.315257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4a8511542e3'
down_revision: Union[str, None] = '3e22308a5d75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens') as batch_op:
        # Add new columns first
        batch_op.add_column(
            sa.Column('access_token', sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column('token_type', sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column('refresh_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_valid', sa.Boolean(), nullable=True))

    # Drop old column and set constraints in separate batch
    with op.batch_alter_table('tokens') as batch_op:
        batch_op.drop_column('token')
        batch_op.alter_column('access_token', nullable=False)
        batch_op.create_unique_constraint(
            'uq_tokens_access_token', ['access_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens') as batch_op:
        batch_op.add_column(sa.Column('token', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint('uq_tokens_access_token', type_='unique')
        batch_op.drop_column('is_valid')
        batch_op.drop_column('refresh_token')
        batch_op.drop_column('token_type')
        batch_op.drop_column('access_token')
        batch_op.alter_column('token', nullable=False)
    # ### end Alembic commands ###
