"""Add usage limits and subscription tracking for dual platform support

Revision ID: c517e4534e6b
Revises: ebc7baf350ef
Create Date: 2025-06-09 16:33:56.434829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c517e4534e6b'
down_revision: Union[str, None] = 'ebc7baf350ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
