"""add_context_metadata_to_generated_scenarios

Revision ID: e001d39f6375
Revises: f576fd6dfc12
Create Date: 2025-08-10 23:48:33.983495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e001d39f6375'
down_revision: Union[str, None] = 'f576fd6dfc12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_scenarios', sa.Column('context_metadata', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_scenarios', 'context_metadata')
    # ### end Alembic commands ###
