"""Add user phone numbers and onboarding tracking

Revision ID: ebc7baf350ef
Revises: 40e131ef24ae
Create Date: 2025-06-08 23:19:18.089162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebc7baf350ef'
down_revision: Union[str, None] = '40e131ef24ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
