"""Add conversation transcript table for calendar integration

Revision ID: f27072552dd3
Revises: 52c42c78dae5
Create Date: 2025-08-28 11:46:42.782206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f27072552dd3'
down_revision: Union[str, None] = '52c42c78dae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
