"""add_anonymous_onboarding_sessions_table

Revision ID: f4dde98c9eae
Revises: 96925727854f
Create Date: 2025-08-20 10:47:36.420340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4dde98c9eae'
down_revision: Union[str, None] = '96925727854f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonymous_onboarding_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('selected_scenario_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anonymous_onboarding_sessions_id'), 'anonymous_onboarding_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_anonymous_onboarding_sessions_session_id'), 'anonymous_onboarding_sessions', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anonymous_onboarding_sessions_session_id'), table_name='anonymous_onboarding_sessions')
    op.drop_index(op.f('ix_anonymous_onboarding_sessions_id'), table_name='anonymous_onboarding_sessions')
    op.drop_table('anonymous_onboarding_sessions')
    # ### end Alembic commands ###
