"""Add multi-tenant SMS bot models

Revision ID: fe0b74938e1a
Revises: bec058360a70
Create Date: 2025-08-27 10:50:44.928781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe0b74938e1a'
down_revision: Union[str, None] = 'bec058360a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_conversations', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sms_conversations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sms_conversations', type_='foreignkey')
    op.drop_column('sms_conversations', 'user_id')
    # ### end Alembic commands ###
